### ISSUE TITLE
login

### ISSUE THREAD

**Issue by arkrausehardie** [GSA/dotgov-home#48]
What happened to the Login Button.  I can't believe you are making us click around all over the screen hoping to find the login scree.  Am I managing a domain And I registering it?  Does it make a difference to logging in?    Only to discover after 5 or 6 random clicks that you take us back to the same old site.   How stupid is that.

And I have to create a github account just to say all this.  Really?   You must not really want to hear what people think.  Because most people won't bother.  I'm not sure why I did, but I was so pissed.

![screen shot 2018-02-09 at 1 30 45 pm](https://user-images.githubusercontent.com/5595621/36043559-a7ba2e1c-0d9d-11e8-9e4f-4102a1eaa2d7.png)

**Comment by konklone** [comment]
Hi @arkrausehardie -- we're sorry this was a frustrating experience, and thanks for taking the time to create a GitHub account to tell us this.

I'm going to work on some changes to make it more over-the-top obvious how to get to the registrar site, and will update here when I have those ready.

I'll also discuss with the team what options we have for encouraging non-GitHub methods of contacting the DotGov program with issues, so that we can hear from as wide an array of DotGov users as possible.

**Comment by arkrausehardie** [comment]
Wow seriously impressed.  Thanks for the quick reply.   I'm so used to feeling that nothing I say makes the slightest difference in the outcomes and you get to be the repository of the frustration!  
Yesterday dotgov.gov took us right to the login page.  Today there's a whole new layer on top.  anyway thanks

**Comment by konklone** [comment]
I can understand the frustration - it was a sudden change. 

If you don't mind, I'll leave this open until we make changes to improve the issues you raised, and then we'll close it.

**Comment by h-m-f-t** [comment]
Hi @arkrausehardie. We've been using this set up for a little over 9 months, and have done our best to streamline all of the .gov program-related content onto this site instead of the registrar.

I'm going to close this issue now, but if you have additional comments, feel free to reopen it. We'd welcome your thoughts.
